"""add bills and bill_texts tables

Revision ID: 67f0b7167479
Revises: 
Create Date: 2026-08-10 18:00:53.729538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f0b7167479'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('bill_id', sa.Text(), nullable=False),
    sa.Column('session', sa.Text(), nullable=False),
    sa.Column('bill_type', sa.Text(), nullable=False),
    sa.Column('bill_number', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('bill_texts',
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.PrimaryKeyConstraint('text_id'),
    sa.UniqueConstraint('bill_id', name='uq_bill_texts_bill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_texts')
    op.drop_table('bills')
    # ### end Alembic commands ###
