"""make minio_key nullable

Revision ID: 71a44ab8b8ba
Revises: c440e5e1245e
Create Date: 2026-08-10 18:56:03.727973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a44ab8b8ba'
down_revision: Union[str, None] = 'c440e5e1245e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'minio_key',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'minio_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
