"""add user_documents table

Revision ID: c440e5e1245e
Revises: 67f0b7167479
Create Date: 2026-08-10 18:37:28.511565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c440e5e1245e'
down_revision: Union[str, None] = '67f0b7167479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('minio_key', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('content_hash', name='uq_user_documents_content_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_documents')
    # ### end Alembic commands ###
